backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "noticias_radio"
    label: "Noticias de la Radio"
    files:
      - file: "content/noticias.json"
        label: "Lista de Noticias y Portada"
        name: "noticias"
        fields:
          - label: "Artículos Publicados"
            name: "articulos"
            widget: "list"
            fields:
              - {label: "Título de la Noticia", name: "title", widget: "string"}
              - {label: "Categoría", name: "category", widget: "select", options: ["Comunidad", "Educación", "Cultura", "Música", "Actualidad", "Deportes"]}
              - {label: "Fecha", name: "date", widget: "datetime"}
              - {label: "Foto / Imagen", name: "image", widget: "image", required: false}
              - {label: "Resumen breve", name: "summary", widget: "text"}
              - {label: "Contenido completo", name: "body", widget: "markdown"}
